### ISSUE TITLE
Customization in Day View.

### ISSUE THREAD

**Issue by JaydipRadadiya** [ptrstovka/calendarview2#7]
Hi 

How can customize the day view with another TextView or any other view.
I am trying to make like this

Thank you Prolific Interactive Team.

![screenshot_20180921-152633](https://user-images.githubusercontent.com/12029999/46125312-2cce0a80-c246-11e8-865e-e022053f511d.png)

**Comment by ptrstovka** [comment]
Hey,

just to make sure, this is a customized version of calendarview from prolific interactive team. I am not related in any way to prolific interactive team.
Here is an original repository https://github.com/prolificinteractive/material-calendarview of the library.

I created a copy with customization because at the time I needed this library, there was no easy way for me to add custom backgrounds for individual day selections, like it is shown in readme art.
(It's possible now using decorators, in prolific version, they already have v2 version, at the time of the mine customization it was v1.)

And back to your issue.
I encourage you, to use prolific version, as they actively support it. You should be able to do it using decorators, https://github.com/prolificinteractive/material-calendarview/wiki/Decorators
You are able to set custom background, selectors and using spans you will be able to add custom text to day views.
